# -*- coding: utf-8 -*-
"""FineTuneusingGEMMA'Smodel.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Tq16l3gQOtZVhxALKlTJR0NcmyQXFBLg

# Finetuning Using Google Gemma's Model
"""

!pip install -q -U bitsandbytes==0.42.0
!pip3 install -q -U peft==0.8.2
!pip install -q -U trl==0.7.10
!pip3 install -q -U accelerate==0.27.1
!pip install -q -U datasets==2.17.0
!pip3 install -q -U transformers==4.38.0

import peft
import trl
import transformers

print("peft:", peft.__version__)
print("trl:", trl.__version__)
print("transformers:", transformers.__version__)

!pip show peft

!pip uninstall -y peft trl transformers accelerate diffusers

!pip install -U peft
!pip install -U trl
!pip install -U transformers
!pip install -U accelerate

import os
import transformers
import torch
from google.colab import userdata
from datasets import load_dataset
from trl import SFTTrainer
from peft import LoraConfig
from transformers import AutoTokenizer, AutoModelForCausalLM
from transformers import BitsAndBytesConfig, GemmaTokenizer

os.environ["HF_TOKEN"] = userdata.get('HF_TOKEN')

"""### Prerequisites
* nf4(4-bit NormalFloat(NF4)) : https://www.kaggle.com/code/lorentzyeung/what-s-4-bit-quantization-how-does-it-help-llama2

"""

model_id = "google/gemma-2b"
bnb_config = BitsAndBytesConfig(
    load_in_4bit = True,
    bnb_4bit_quant_type="nf4",
    bnb_4bit_compute_dtype=torch.bfloat16
)

"""okenizer = AutoTokenizer.from_pretrained(model_id, token=os.environ['HF_TOKEN'])
model = AutoModelForCausalLM.from_pretrained(model_id,
                                             quantization_config=bnb_config,
                                             device_map={"":0},
                                             token=os.environ['HF_TOKEN'])
HTTPStatusError: Client error '403 Forbidden' for url 'https://huggingface.co/google/gemma-2b/resolve/main/config.json'
For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/403

The above exception was the direct cause of the following exception:

GatedRepoError                            Traceback (most recent call last)
GatedRepoError: 403 Client Error. (Request ID: Root=1-6a2a9530-4daadf773aa9afab62aa3c25;f8512f8a-8fff-41e0-bba3-89b07d451510)

Cannot access gated repo for url https://huggingface.co/google/gemma-2b/resolve/main/config.json.
Access to model google/gemma-2b is restricted and you are not in the authorized list. Visit https://huggingface.co/google/gemma-2b to ask for access.

The above exception was the direct cause of the following exception:

OSError                                   Traceback (most recent call last)
OSError: You are trying to access a gated repo.
Make sure to have access to it at https://huggingface.co/google/gemma-2b.
403 Client Error. (Request ID: Root=1-6a2a9530-4daadf773aa9afab62aa3c25;f8512f8a-8fff-41e0-bba3-89b07d451510)

Cannot access gated repo for url https://huggingface.co/google/gemma-2b/resolve/main/config.json.
Access to model google/gemma-2b is restricted and you are not in the authorized list. Visit https://huggingface.co/google/gemma-2b to ask for access.

During handling of the above exception, another exception occurred:

HTTPStatusError                           Traceback (most recent call last)
HTTPStatusError: Client error '403 Forbidden' for url 'https://huggingface.co/google/gemma-2b/resolve/main/config.json'
For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/403

The above exception was the direct cause of the following exception:

GatedRepoError                            Traceback (most recent call last)
GatedRepoError: 403 Client Error. (Request ID: Root=1-6a2a9532-615058aa08232ca271c0506c;07e62933-3085-4039-944a-992793c309a0)

Cannot access gated repo for url https://huggingface.co/google/gemma-2b/resolve/main/config.json.
Access to model google/gemma-2b is restricted and you are not in the authorized list. Visit https://huggingface.co/google/gemma-2b to ask for access.

The above exception was the direct cause of the following exception:

OSError                                   Traceback (most recent call last)
/usr/local/lib/python3.12/dist-packages/transformers/utils/hub.py in cached_files(path_or_repo_id, filenames, cache_dir, force_download, proxies, token, revision, local_files_only, subfolder, repo_type, user_agent, _raise_exceptions_for_gated_repo, _raise_exceptions_for_missing_entries, _raise_exceptions_for_connection_errors, _commit_hash, tqdm_class, **deprecated_kwargs)
    501             if not _raise_exceptions_for_gated_repo:
    502                 return None
--> 503             raise OSError(
    504                 "You are trying to access a gated repo.\nMake sure to have access to it at "
    505                 f"https://huggingface.co/{path_or_repo_id}.\n{str(e)}"

OSError: You are trying to access a gated repo.
Make sure to have access to it at https://huggingface.co/google/gemma-2b.
403 Client Error. (Request ID: Root=1-6a2a9532-615058aa08232ca271c0506c;07e62933-3085-4039-944a-992793c309a0)

Cannot access gated repo for url https://huggingface.co/google/gemma-2b/resolve/main/config.json.
Access to model google/gemma-2b is restricted and you are not in the authorized list. Visit https://huggingface.co/google/gemma-2b to ask for access.

Your code is correct now. The problem is not the token code. The error says:

Cannot access gated repo for url https://huggingface.co/google/gemma-2b
Access to model google/gemma-2b is restricted and you are not in the authorized list

You created the Hugging Face token, but your Hugging Face account has not accepted access to Gemma.

Do this:

1. Open Gemma model page

Go here:

https://huggingface.co/google/gemma-2b

Make sure you are logged in with the same account (nidhisah88).

You will see something like:

Access Gemma
Agree and access repository

Click:

Agree and access repository

Accept Google's license.

2. Check access

After accepting, open:

https://huggingface.co/settings/gated-repos

You should see:

google/gemma-2b     Access granted
3. Re-login in Colab

Restart runtime:

Runtime → Restart session

Then:

from huggingface_hub import login
from google.colab import userdata
import os

HF_TOKEN = userdata.get("HF_TOKEN")

login(HF_TOKEN)

os.environ["HF_TOKEN"] = HF_TOKEN
4. Test access

Run:

from huggingface_hub import whoami

print(whoami())

You should see your HF username.

Then:

from huggingface_hub import model_info

model_info(
    "google/gemma-2b",
    token=os.environ["HF_TOKEN"]
)

If it works, you will get model details.

5. Load model again
model_id = "google/gemma-2b"

tokenizer = AutoTokenizer.from_pretrained(
    model_id,
    token=os.environ["HF_TOKEN"]
)

model = AutoModelForCausalLM.from_pretrained(
    model_id,
    quantization_config=bnb_config,
    device_map="auto",
    token=os.environ["HF_TOKEN"]
)

One more thing: for fine-tuning in 2026, google/gemma-2b is an older Gemma model. You may prefer:

model_id = "google/gemma-2-2b"

or

model_id = "google/gemma-2-9b"

after accepting access on that model page too. The same token will work.
"""

import torch

print(torch.cuda.is_available())
print(torch.version.cuda)
print(torch.cuda.get_device_name(0))

!pip uninstall -y bitsandbytes
!pip install bitsandbytes==0.46.1

import bitsandbytes

print(bitsandbytes.__version__)

# !pip install -U bitsandbytes

import bitsandbytes

print(bitsandbytes.__version__)



tokenizer = AutoTokenizer.from_pretrained(model_id, token=os.environ['HF_TOKEN'])
model = AutoModelForCausalLM.from_pretrained(model_id,
                                             quantization_config=bnb_config,
                                             device_map={"":0},
                                             token=os.environ['HF_TOKEN'])

text = "Quote: Imagination is more,"
device = "cuda:0"
inputs = tokenizer(text, return_tensors="pt").to(device)

outputs = model.generate(**inputs, max_new_tokens=20)
print(tokenizer.decode(outputs[0], skip_special_tokens=True))

os.environ["WANDB_DISABLED"] = "false"

lora_config = LoraConfig(
    r = 8,
    target_modules = ["q_proj", "o_proj", "k_proj", "v_proj",
                      "gate_proj", "up_proj", "down_proj"],
    task_type = "CAUSAL_LM",
)

from datasets import load_dataset

data = load_dataset("Abirate/english_quotes")
data = data.map(lambda samples: tokenizer(samples["quote"]), batched=True)

data['train']['quote']

def formatting_func(example):
    text = f"Quote: {example['quote'][0]}\nAuthor: {example['author'][0]}"
    return [text]

data['train']

trainer = SFTTrainer(
    model=model,
    train_dataset=data["train"],
    args=transformers.TrainingArguments(
        per_device_train_batch_size=1,
        gradient_accumulation_steps=4,
        warmup_steps=2,
        max_steps=100,
        learning_rate=2e-4,
        # fp16=True,
        fp16=False,
        bf16=True,
        logging_steps=1,
        output_dir="outputs",
        optim="paged_adamw_8bit"
    ),
    peft_config=lora_config,
    formatting_func=formatting_func,
)

trainer.train()

text = "Quote: A woman is like a tea bag;"
device = "cuda:0"
inputs = tokenizer(text, return_tensors="pt").to(device)

outputs = model.generate(**inputs, max_new_tokens=20)
print(tokenizer.decode(outputs[0], skip_special_tokens=True))

text = "Quote: Outside of a dog, a book is man's"
device = "cuda:0"
inputs = tokenizer(text, return_tensors="pt").to(device)

outputs = model.generate(**inputs, max_new_tokens=20)
print(tokenizer.decode(outputs[0], skip_special_tokens=True))





